spring:
  application:
    name: avatar-coach

  profiles:
    default: local

  jpa:
    open-in-view: false

gcp:
  storage:
    enabled: ${GCS_STORAGE_ENABLED:false}
    bucket-name: ${GCS_BUCKET_NAME:avatar-coach-documents-local}
    document-prefix: ${GCS_DOCUMENT_PREFIX:documents}
    signed-url-expiration-minutes: ${GCS_SIGNED_URL_EXPIRATION_MINUTES:10}


server:
  port: ${PORT:8080}
