CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE public.global_corpus_sources
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       timestamp(6) without time zone NOT NULL,
    source_key       varchar(150)                            NOT NULL,
    source_title     varchar(255),
    source_license   varchar(100),
    artifact_name    varchar(255),
    artifact_version varchar(100),
    artifact_variant varchar(100),
    artifact_uri     varchar(1000),
    metadata_json    jsonb                                   NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE ONLY public.global_corpus_sources
    ADD CONSTRAINT global_corpus_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.global_corpus_sources
    ADD CONSTRAINT uk_global_corpus_sources_source_key UNIQUE (source_key);

CREATE TABLE public.global_corpus_records
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           timestamp(6) without time zone NOT NULL,
    source_id            bigint                                  NOT NULL,
    record_id            varchar(150)                            NOT NULL,
    request_id           varchar(100),
    target               varchar(30)                             NOT NULL,
    language             varchar(10)                             NOT NULL DEFAULT 'ko',
    record_type          varchar(50)                             NOT NULL,
    difficulty           varchar(30),
    topic_path           jsonb                                   NOT NULL DEFAULT '[]'::jsonb,
    tags                 jsonb                                   NOT NULL DEFAULT '[]'::jsonb,
    followup_strategy    varchar(50),
    embedding_text_ko    text                                    NOT NULL,
    question_ko          text,
    answer_ko            text,
    followup_question_ko text,
    concept_ko           text,
    interview_use        text,
    rubric               jsonb                                   NOT NULL DEFAULT '{}'::jsonb,
    followup_pattern_ext jsonb                                   NOT NULL DEFAULT '{}'::jsonb,
    source_refs          jsonb                                   NOT NULL DEFAULT '[]'::jsonb,
    quality              jsonb                                   NOT NULL DEFAULT '{}'::jsonb,
    created_by           jsonb                                   NOT NULL DEFAULT '{}'::jsonb,
    embedding            vector(1024),
    CONSTRAINT global_corpus_records_target_check CHECK (
        target IN ('BACKEND', 'FRONTEND', 'FULLSTACK', 'AI_ML', 'DATA', 'DEVOPS', 'MOBILE', 'QA')
        ),
    CONSTRAINT global_corpus_records_language_check CHECK (
        language IN ('ko', 'en')
    ),
    CONSTRAINT global_corpus_records_difficulty_check CHECK (
        difficulty IS NULL OR difficulty IN ('EASY', 'NORMAL', 'HARD')
    )
);

ALTER TABLE ONLY public.global_corpus_records
    ADD CONSTRAINT global_corpus_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.global_corpus_records
    ADD CONSTRAINT uk_global_corpus_records_record_id UNIQUE (record_id);

ALTER TABLE ONLY public.global_corpus_records
    ADD CONSTRAINT fk_global_corpus_records_source
    FOREIGN KEY (source_id) REFERENCES public.global_corpus_sources(id);

CREATE INDEX idx_global_corpus_records_filter
    ON public.global_corpus_records (target, language, record_type, difficulty);

CREATE INDEX idx_global_corpus_records_source_id
    ON public.global_corpus_records (source_id);

CREATE INDEX idx_global_corpus_records_followup_strategy
    ON public.global_corpus_records (followup_strategy);

CREATE INDEX idx_global_corpus_records_topic_path_gin
    ON public.global_corpus_records USING gin (topic_path);

CREATE INDEX idx_global_corpus_records_tags_gin
    ON public.global_corpus_records USING gin (tags);

CREATE INDEX idx_global_corpus_records_embedding_hnsw
    ON public.global_corpus_records
    USING hnsw (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL;

CREATE TABLE public.global_corpus_source_chunks
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           timestamp(6) without time zone NOT NULL,
    source_id            bigint                                  NOT NULL,
    source_chunk_id      varchar(200)                            NOT NULL,
    target               varchar(30)                             NOT NULL,
    source_key           varchar(150)                            NOT NULL,
    source_title         varchar(255),
    source_type          varchar(100),
    source_url           varchar(1000),
    source_version       varchar(255),
    source_license       varchar(100),
    chunk_index          integer,
    heading_path         jsonb                                   NOT NULL DEFAULT '[]'::jsonb,
    text                 text                                    NOT NULL,
    text_hash            varchar(100),
    source_hash          varchar(100),
    raw_text_hash        varchar(100),
    normalized_text_hash varchar(100),
    metadata_json        jsonb                                   NOT NULL DEFAULT '{}'::jsonb,
    source_refs          jsonb                                   NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT global_corpus_source_chunks_target_check CHECK (
        target IN ('BACKEND', 'FRONTEND', 'FULLSTACK', 'AI_ML', 'DATA', 'DEVOPS', 'MOBILE', 'QA')
        )
);

ALTER TABLE ONLY public.global_corpus_source_chunks
    ADD CONSTRAINT global_corpus_source_chunks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.global_corpus_source_chunks
    ADD CONSTRAINT uk_global_corpus_source_chunks_chunk_id UNIQUE (source_chunk_id);

ALTER TABLE ONLY public.global_corpus_source_chunks
    ADD CONSTRAINT fk_global_corpus_source_chunks_source
    FOREIGN KEY (source_id) REFERENCES public.global_corpus_sources(id);

CREATE INDEX idx_global_corpus_source_chunks_source_id
    ON public.global_corpus_source_chunks (source_id);

CREATE INDEX idx_global_corpus_source_chunks_target_source_key
    ON public.global_corpus_source_chunks (target, source_key);

CREATE INDEX idx_global_corpus_source_chunks_heading_path_gin
    ON public.global_corpus_source_chunks USING gin (heading_path);
